### ISSUE TITLE
Command 'PlayCanvas: Add project' resulted in an error

### ISSUE THREAD

**Issue by kidcry0x** [playcanvas/vscode-extension#6]
![image](https://github.com/playcanvas/vscode-extension/assets/61981331/a0d96d27-0003-4126-829c-47e46464d917)

I got this error after selecting the "PlayCanvas: Add Project" command in the VS Code command menu. I entered my PlayCanvas token and username on the extension settings page earlier

**Comment by Sceat** [comment]
Yeah actually that's what I got in https://github.com/playcanvas/vscode-extension/issues/5 thought it was solved but I got the error again so..

**Comment by kidcry0x** [comment]
I tried fixing it your way of adding the script and restarting vscode but it still doesn't work :(

**Comment by slimbuck** [comment]
cc @isumygin-sc

**Comment by icameron** [comment]
Not sure if its related but [Extension Host] API call failed: Error: Forbidden shows in the logs

**Comment by isumygin-sc** [comment]
the issue is fixed, please reload VS Code

**Comment by Zh-eng-yi** [comment]
I reloaded VS Code and PlayCanvas plugin but still got this error... wondering if anyone is still facing it?

**Comment by 10xRod** [comment]
> Not sure if its related but [Extension Host] API call failed: Error: Forbidden shows in the logs

Forbidden suggests bad key or username

I know this sounds obvious but I found my way here researching a fix for what I thought was this issue. Solved my `Error: Forbidden` by double checking the username I put in the VS Code extension settings exactly matched user from account profile page on PlayCanvas website. Turns out there was a character missing... RTFM type situation 🤭

Hope it helps

**Comment by willeastcott** [comment]
Close now that this is logged: https://github.com/playcanvas/vscode-extension/issues/7
